framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

            async_normal:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    table_name: async_jobs
                    queue_name: normal_priority

                # default configuration
                retry_strategy:
                    max_retries: 3
                    # milliseconds delay
                    delay: 1000
                    # causes the delay to be higher before each retry
                    # e.g. 1 second delay, 2 seconds, 4 seconds
                    multiplier: 2
                    max_delay: 0

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': sync
            # 'App\Message\YourMessage': async
            'App\Message\Task01':  async_normal
            'App\Message\Task02':  async_normal