language: php

php:
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4

services:
  - redis-server

matrix:
  include:
  allow_failures:
  - php: 7.0
  - php: 7.1

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - sudo apt-get update
  - sudo apt-get install -y php-redis
  - echo "extension=redis.so" >> $(php --ini | grep Loaded | cut -d" " -f12)
  - php -ini

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - export APP_ENV=test
  - make ci
  - make installed
  - make outdated